export const reconciliationData = [
  {
    orderId: 'ORD001',
    collectorId: 'COLL001',
    totalValue: '₹1500.00',
    settlementAmount: '₹1173.00',
    commission: '₹150.00',
    orderStatus: 'Not Settled',
    error: 'Settlement AP Timeout',
  },
  {
    orderId: 'ORD002',
    collectorId: 'COLL001',
    totalValue: '₹1500.00',
    settlementAmount: '₹1173.00',
    commission: '₹150.00',
    orderStatus: 'Not Settled',
    error: 'Invalid Bank Details',
  },
  {
    orderId: 'ORD003',
    collectorId: 'COLL001',
    totalValue: '₹1500.00',
    settlementAmount: '₹1173.00',
    commission: '₹150.00',
    orderStatus: 'Not Settled',
    error: 'Settlement AP Timeout',
  },
  {
    orderId: 'ORD004',
    collectorId: 'COLL001',
    totalValue: '₹1500.00',
    settlementAmount: '₹1173.00',
    commission: '₹150.00',
    orderStatus: 'Not Settled',
    error: 'Insufficient balance',
  },
  {
    orderId: 'ORD005',
    collectorId: 'COLL001',
    totalValue: '₹1500.00',
    settlementAmount: '₹1173.00',
    commission: '₹150.00',
    orderStatus: 'Not Settled',
    error: 'Settlement AP Timeout',
  },
]

export const outgoingRequestsData = [
  {
    orderId: 'ORD001',
    receiverId: 'RECV001',
    status: 'Accepted',
    dueDate: '2024-01-20',
    response: 'Accepted with revised due date',
    actions: ['Move to Ready'],
    error: '',
  },
  {
    orderId: 'ORD002',
    receiverId: 'RECV001',
    status: 'Rejected',
    dueDate: '2024-01-20',
    response: 'Accepted with revised due date',
    actions: ['Reinitiate', 'IGM Complaint'],
    error: 'IGM Complaint',
  },
  {
    orderId: 'ORD003',
    receiverId: 'RECV001',
    status: 'Accepted',
    dueDate: '2024-01-20',
    response: 'Accepted with revised due date',
    actions: ['Move to Ready'],
    error: '',
  },
  {
    orderId: 'ORD004',
    receiverId: 'RECV001',
    status: 'Rejected',
    dueDate: '2024-01-20',
    response: 'Accepted with revised due date',
    actions: ['Reinitiate', 'IGM Complaint'],
    error: 'IGM Complaint',
  },
  {
    orderId: 'ORD005',
    receiverId: 'RECV001',
    status: 'Accepted',
    dueDate: '2024-01-20',
    response: 'Accepted with revised due date',
    actions: ['Move to Ready'],
    error: '',
  },
]
