export enum APIRoute {
  USERS = '/ui/users',
  SETTLEMENTS_PAYLOAD = '/ui/rsf-payloads',
  GENERATE_MISC = '/ui/generate/{userId}/settle/misc',
  GENERATE_NIL = '/ui/generate/{userId}/settle/nil',
  GENERATE_NP_NP = '/ui/generate/{userId}/settle/np-np',
  TRIGGER_ACTION = '/ui/trigger/{userId}/{action}',
  ORDERS = '/ui/orders/{userId}',
  SETTLE_PREPARE = '/ui/settle/{userId}/prepare',
  SETTLEMENT = '/ui/settle/{userId}',
  GENERATE_RECON = '/ui/generate/{userId}/recon',
  RECON = '/ui/recon/{userId}',
  MOVE_TO_READY = '/ui/recon/{userId}/move-to-ready',
  ON_RECON = '/ui/generate/{userId}/on_recon',
  SIGN_TOKEN = 'ui/auth/sign-token',
}
