export enum TypographyVariant {
  H1 = 'h1',
  H2 = 'h2',
  H3 = 'h3',
  H3Semibold = 'h3_semibold',
  H4 = 'h4',
  H5 = 'h5',
  H5Semibold = 'h5_semibold',
  H5Bold = 'h5_bold',
  H6 = 'h6',
  H6Semibold = 'h6_semibold',
  H6Bold = 'h6_bold',
  Body1 = 'body1',
  Body1Regular = 'body1_regular',
  Body1Medium = 'body1_medium',
  Body2 = 'body2',
  Body2Regular = 'body2_regular',
  Body2Semibold = 'body2_semibold',
  Body2Medium = 'body2_medium',
  Body5Light = 'body5_light',
  Body5Medium = 'body5_medium',
  Body5Regular = 'body5_regular',
  Body5Semibold = 'body5_semibold',
  Caption1 = 'caption1',
  Caption1Semibold = 'caption1_semibold',
}
