export const DOMAIN_CATEGORIES = [
  { value: 'ONDC:RET10', label: 'Grocery' },
  { value: 'ONDC:RET11', label: 'Food & Beverages' },
  { value: 'ONDC:RET12', label: 'Fashion' },
  { value: 'ONDC:RET13', label: 'Beauty & Personal Care' },
  { value: 'ONDC:RET14', label: 'Electronics' },
  { value: 'ONDC:RET15', label: 'Appliances' },
  { value: 'ONDC:RET16', label: 'Home & Kitchen' },
  { value: 'ONDC:RET18', label: 'Health & Wellness' },
  { value: 'ONDC:RET1A', label: 'Automotives, Components & Accessories' },
  { value: 'ONDC:RET1B', label: 'Hardware and Industrial' },
  { value: 'ONDC:RET1C', label: 'Building and construction supplies' },
  { value: 'ONDC:RET1D', label: 'Chemicals' },
  { value: 'ONDC:RET1E', label: 'Packaging Product' },
  { value: 'nic2004:60232', label: 'Logistics' },
  { value: 'ONDC:LOG10', label: 'P2P' },
  { value: 'ONDC:LOG11', label: 'P2H2P' },
]

export const DOMAIN_CATEGORY_LABELS: Record<string, string> = {
  'ONDC:RET10': 'Grocery',
  'ONDC:RET11': 'Food & Beverages',
  'ONDC:RET12': 'Fashion',
  'ONDC:RET13': 'Beauty & Personal Care',
  'ONDC:RET14': 'Electronics',
  'ONDC:RET15': 'Appliances',
  'ONDC:RET16': 'Home & Kitchen',
  'ONDC:RET18': 'Health & Wellness',
  'ONDC:RET1A': 'Automotives, Components & Accessories',
  'ONDC:RET1B': 'Hardware and Industrial',
  'ONDC:RET1C': 'Building and construction supplies',
  'ONDC:RET1D': 'Chemicals',
  'ONDC:RET1E': 'Packaging Product',
  'nic2004:60232': 'Logistics',
  'ONDC:LOG10': 'P2P',
  'ONDC:LOG11': 'P2H2P',
}
