export const TABLE_STYLING = {
  CHECKBOX_CELL_WIDTH: '48px',
  CELL_PADDING: '16px',
  BORDER_RADIUS: 8,
  TABLE_HEAD_BACKGROUND: '#f5f5f5',
  HEADER_CELL_GAP: '4px',
  ICON_BUTTON_PADDING: '2px',
  WRAPPER_PADDING: '0 24px',
} as const
